In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

In [2]:
class ChicagoAssessorData():
    def __init__(self):
        self.ChicagoRealtyData = pd.read_csv("ChicagoRealty.csv")
        #self.dept_numbers_path = "https://www.deptofnumbers.com/"
        #self.dn_jobs_path = "employment/metros/"
        #self.get_soup()
        #self.get_month()
        
    def get_soup(self):       
        page = requests.get(self.dept_numbers_path + self.dn_jobs_path)
        soup = BeautifulSoup(page.text, 'html.parser')
        self.soup = soup
        
    def get_month(self):
        table = self.soup.find('table', {'id': 'metro_table'})
        table_rows = table.find_all('th')
        self.month = table_rows[1].text[:-16]
    
    @staticmethod
    def get_table(table_rows):
        l = []
        for tr in table_rows:
            td = tr.find_all('td')
            row = [tr.text.strip(" %") for tr in td if tr.text.strip()]
            l.append(row)
        return l

In [3]:
data = ChicagoAssessorData()
df = data.ChicagoRealtyData

/Users/nelsonlin/opt/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3249: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [36]:
df.columns

Index(['Pin', 'Address.Line1', 'Address.Line2', 'Address.CityStateZip',
       'Address.HouseAlpha', 'Address.HouseNumber', 'Address.StreetDirection',
       'Address.StreetName', 'Address.StreetSuffix', 'Address.Apartment',
       'Address.City', 'Address.State', 'Address.Zip', 'Address.Township',
       'Classification', 'CurrentValue.LandValue',
       'CurrentValue.BuildingValue', 'CurrentValue.TotalValue',
       'CurrentValue.MarketValue', 'Characteristics.Classification',
       'Characteristics.ClassificationDescription',
       'Characteristics.FullBaths', 'Characteristics.HalfBaths',
       'Characteristics.AirConditioning', 'Characteristics.FirePlaces',
       'Characteristics.IsLandmark', 'Characteristics.ResidenceUse',
       'Characteristics.ResidenceUseDescription',
       'Characteristics.ResidenceType',
       'Characteristics.ResidenceTypeDescription',
       'Characteristics.Apartments', 'Characteristics.Basement',
       'Characteristics.BasementDescription', 'Characteristics.Garage',
       'Characteristics.GarageDescription', 'Characteristics.Attic',
       'Characteristics.AtticDescription', 'Characteristics.Construction',
       'Characteristics.ConstructionDescription', 'Characteristics.CommUnits',
       'Characteristics.CommUnitsDescription',
       'Characteristics.BuildingSquareFootage',
       'Characteristics.LandSquareFootage'],
      dtype='object')

In [30]:
df["Address.Township"].unique()

array(['Evanston', 'Niles', 'Norwood Park', 'Oak Park', 'River Forest',
       'Schaumburg', 'Wheeling', 'Hyde Park', 'HydePark', 'Jefferson',
       'Lake View', 'LakeView', 'North Chicago', 'NorthChicago',
       'Rogers Park', 'RogersPark', 'South Chicago', 'SouthChicago',
       'West Chicago', 'WestChicago', 'Lake'], dtype=object)

In [28]:
df["Address.CityStateZip"].unique()

array(['EVANSTON, IL 60201', 'EVANSTON, IL 0', 'EVANSTON, IL 60202',
       'EVANSTON, IL 60208', 'UNKNOWN, IL 0', ', IL 0', 'NILES, IL 60714',
       'NILES, IL 60631', 'GLENVIEW, IL 60025', 'GLENVIEW, IL 0',
       'GOLF, IL 60029', 'MORTON GROVE, IL 60053', 'SKOKIE, IL 60077',
       'SKOKIE, IL 0', 'SKOKIE, IL 60076', 'CHICAGO, IL 0',
       'MORTONGROVE, IL 60053', 'EVANSTON, IL 60203', 'LINCOLNWOOD, IL 0',
       'LINCOLNWOOD, IL 60712', 'CHICAGO, IL 60712', 'NILES, IL 60646',
       'LINCOLNWOOD, IL 60714', 'CHICAGO, IL 60646', 'GLENVIEW, IL 60026',
       'NILES, IL 60712', 'NORRIDGE, IL 60706', 'NORRIDGE, IL 0',
       'HARWOOD HEIGHTS, IL 60706', 'HARWOOD HEIGHTS, IL 60656',
       'HARWOOD HEIGHTS, IL 0', 'HARWOOD HEIGHTS, IL 60631',
       'HARWOOD HEIGHTS, IL 60714', 'CHICAGO, IL 60706',
       'NORRIDGE, IL 60656', 'HARWOOD HEIGHTS, IL 60634',
       'PARK RIDGE, IL 60068', 'NORWOOD PARK, IL 60631',
       'CHICAGO, IL 60631', 'NORWOOD PARK, IL 60656', 'CHICAGO, IL 60656',
       'OAK PARK, IL 60302', 'OAK PARK, IL 0', 'OAK PARK, IL 60305',
       'OAK PARK, IL 60301', 'OAK PARK, IL 60304', 'UNKNOWN, IL 60304',
       'RIVER FOREST, IL 60305', 'RIVER FOREST, IL 60302',
       'HOFFMAN ESTATES, IL 60169', 'HOFFMAN ESTATES, IL 0',
       'SCHAUMBURG, IL 0', 'SCHAUMBURG, IL 60169', 'SCHAUMBURG, IL 60195',
       'SCHAUMBURG, IL 60194', 'SCHAUMBURG, IL 60193',
       'SCHAUMBURG, IL 60173', 'HOFFMANESTATES, IL 60169',
       'HOFFMAN ESTATES, IL 60010', 'HOFFMAN ESTATES, IL 60067',
       'HOFFMAN ESTATES, IL 60195', 'HANOVER PARK, IL 60133',
       'HANOVER PARK, IL 60107', 'UNIC, IL 0', 'STREAMWOOD, IL 60107',
       'ROSELLE, IL 60172', 'SCHAUMBURG, IL 60172', 'ROSELLE, IL 60193',
       'ELK GROVE VILLAGE, IL 0', 'ELK GROVE VILLAGE, IL 60007',
       'UNIC, IL 60172', 'ELGIN, IL 0', 'HOFFMANESTATES, IL 0',
       'TEMP, IL 60173', 'PALATINE, IL 60067', 'SCHAUMBURG, IL 60196',
       'HOFFMAN ESTATES, IL 60192', 'PROSPECT HEIGHTS, IL 60070',
       'MOUNT PROSPECT, IL 60056', 'WHEELING, IL 60090',
       'DES PLAINES, IL 60016', 'DES PLAINES, IL 0',
       'BUFFALO GROVE, IL 60089', 'NORTHBROOK, IL 0',
       'NORTHBROOK, IL 60062', 'ARLINGTON HEIGHTS, IL 0',
       'ARLINGTON HEIGHTS, IL 60004', 'ARLINGTON HEIGHTS, IL 60005',
       'PALATINE, IL 0', 'ROLLING MEADOWS, IL 60008',
       'ARLINGTONHEIGHTS, IL 60004', 'ROLLING MEADOWS, IL 60005',
       'PALATINE, IL 60074', 'PROSPECTHEIGHTS, IL 60070',
       'MOUNTPROSPECT, IL 60056', 'ARLINGTONHEIGHTS, IL 60005',
       'ARLINGTON HEIGHTS, IL 60007', 'ARLINGTONHEIGHTS, IL 0',
       'CHICAGO, IL 60653', 'CHICAGO, IL 60615', 'CHICAGO, IL 60609',
       'CHICAGO, IL 60619', 'CHICAGO, IL 60605', 'CHICAGO, IL 60637',
       'CHICAGO, IL 60616', 'CHICAGO, IL 60621', 'CHICAGO, IL 60603',
       'CHICAGO, IL 60804', 'CHICAGO, IL 60649', 'CHICAGO, IL 60617',
       'CHICAGO, IL 60636', 'CHICAGO, IL 60628', 'CHICAGO, IL 60643',
       'CHICAGO, IL 60805', 'CHICAGO, IL 60620', 'CHICAGO, IL 60827',
       'CHICAGO, IL 60647', 'CHICAGO, IL 60633', 'CHICAGO, IL 60630',
       'CHICAGO, IL 60651', 'CHICAGO, IL 60659', 'CHICAGO, IL 60625',
       'CHICAGO, IL 60641', 'CHICAGO, IL 60624', 'CHICAGO, IL 60645',
       'CHICAGO, IL 60618', 'CHICAGO, IL 60634', 'CHICAGO, IL 60639',
       'CHICAGO, IL 60613', 'CHICAGO, IL 60629', 'CHICAGO, IL 60707',
       'CHICAGO, IL 60612', 'CHICAGO, IL 60622', 'CHICAGO, IL 60614',
       'CHICAGO, IL 60657', 'CHICAGO, IL 60610', 'CHICAGO, IL 60642',
       'CHICAGO, IL 60611', 'CHICAGO, IL 60654', 'CHICAGO, IL 60602',
       'CHICAGO, IL 60607', 'CHICAGO, IL 60601', 'CHICAGO, IL 60606',
       'CHICAGO, IL 60626', 'CHICAGO, IL 60660', 'CHICAGO, IL 60661',
       'CHICAGO, IL 60604', 'CHICAGO, IL 60608', 'CHICAGO, IL 60623',
       'CHICAGO, IL 60632', 'CHICAGO, IL 60644', 'CHICAGO, IL 60638',
       'UNKNOWN, IL 60608', 'CHICAGO, IL 60714', 'CHICAGO, IL 60666',
       'CHICAGO, IL 60652', 'UNKNOWN, IL 60643', 'CHICAGO, IL 60803',
       'CHICAGO, IL 60655', 'CHICAGO, IL 60640'], dtype=object)

In [32]:
commercial_apartments_df = df[(df.Classification >= 300) & (df.Classification <400)]
chicago_apartments_df = commercial_apartments_df[commercial_df["Address.CityStateZip"].str.contains("CHICAGO, IL")]

In [35]:
chicago_apartments_df

,Pin,Address.Line1,Address.Line2,Address.CityStateZip,Address.HouseAlpha,Address.HouseNumber,Address.StreetDirection,Address.StreetName,Address.StreetSuffix,Address.Apartment,...,Characteristics.Garage,Characteristics.GarageDescription,Characteristics.Attic,Characteristics.AtticDescription,Characteristics.Construction,Characteristics.ConstructionDescription,Characteristics.CommUnits,Characteristics.CommUnitsDescription,Characteristics.BuildingSquareFootage,Characteristics.LandSquareFootage
78024,13181001040000,7005 N ELSTON AVE,NaN,"CHICAGO, IL 0",7005,7005,N,ELSTON,AVE,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,7832
213177,20021020310000,846 E 40TH ST,NaN,"CHICAGO, IL 60653",846,846,E,40TH,ST,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,14000
213396,20021060090000,4033 S DREXEL BLVD,NaN,"CHICAGO, IL 60653",4033,4033,S,DREXEL,BLVD,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,9000
213457,20021070010000,4001 S ELLIS AVE,NaN,"CHICAGO, IL 60653",4001,4001,S,ELLIS,AVE,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,25380
213458,20021070020000,4013 S ELLIS AVE,NaN,"CHICAGO, IL 60653",4013,4013,S,ELLIS,AVE,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,10620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128311,14281160310000,2904 N BROADWAY ST,NaN,"CHICAGO, IL 60657",2904,2904,N,BROADWAY,ST,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,12623
1128331,14281200110000,621 W SURF ST,NaN,"CHICAGO, IL 60657",621,621,W,SURF,ST,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,5900
1128335,14281200190000,2843 N CLARK ST,NaN,"CHICAGO, IL 60657",2843,2843,N,CLARK,ST,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,3925
1128336,14281200200000,2839 N CLARK ST,NaN,"CHICAGO, IL 60657",2839,2839,N,CLARK,ST,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,5287
1128337,14281200210000,2835 N CLARK ST,NaN,"CHICAGO, IL 60657",2835,2835,N,CLARK,ST,NaN,...,0,None,0,None,0,NaN,NaN,NaN,0,4537